[versions]
agp = "8.9.3"
kotlin = "2.0.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.01"
devtoolsKsp = "2.0.0-1.0.22"
navigation = "2.9.5"
hilt = "2.57.2"
coil = "2.7.0"
lottie = "6.7.0"
hiltNavigationCompose = "1.3.0"
retrofit = "2.9.0"
retrofitGsonConverter = "2.9.0"
retrofitInterceptor = "5.0.0-alpha.2"
room = "2.6.1"
mockito = "4.0.0"
mockitoInline = "4.4.0"
coroutinesTest = "1.6.4"
roboelectricVersion = "4.8.2"
testCoreKtx = "1.7.0"
archCoreTesting = "2.2.0"
appcompat = "1.7.1"
material = "1.13.0"
animationGraphics = "1.9.4"
constraintlayoutCompose = "1.1.1"

[libraries]

#lifecycle
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

#Core libraries
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

#Navigation
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

#Dependency Injection
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

#Presentation
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
androidx-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics", version.ref = "animationGraphics" }

#Compose
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }

#Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitGsonConverter" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "retrofitInterceptor" }

#Room
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

#Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "testCoreKtx" }
androidx-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "testCoreKtx" }
androidx-archCore-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "archCoreTesting" }

#Mockito
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoInline" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockitoInline" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }

#Robolectric
robokectric-test = { group = "org.robolectric", name = "robolectric", version.ref = "roboelectricVersion" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "devtoolsKsp" }